### ISSUE TITLE
Card content out of the component

### ISSUE THREAD

**Issue by krakowdeveloper** [ariannargesi/quickcomponent.io#2]
- Maybe you can check when the component has some content, assigning an auto context for the height, which will improve all content inside leaving wrapped the content. Basically just checking if the content is wrapped inside the component.
![Screen Shot 2022-04-15 at 11 03 34 AM](https://user-images.githubusercontent.com/14529200/163551187-e5d72b3a-1639-469f-a5cd-91411339d176.png)

**Comment by ariannargesi** [comment]
Hey 
Sorry for responding too late.
You can easy solve this issue by removing height property from your element. Just select your element (In this case root container) and remove height property from active styles section
